name: xiaaaml_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.9.*
  - pip=20.2.4

  - pip:
      # AzureML packages
      - azureml-sdk
      - azureml-defaults
      - scikit-learn
      - inference-schema[numpy-support]
      - joblib

      # Required packages
      - pandas==1.1.3
      - absl-py>=0.12.0
      - chex>=0.0.7
      - clu>=0.0.3
      - einops>=0.3.0
      - flax==0.3.3
      - ml-collections==0.1.0
      - numpy>=1.19.5
      - tensorflow>=2.0.0-beta1
      - jax==0.4.23
      - jaxlib==0.4.23

      # Other packages
      - tqdm~=4.64.1
      - pillow~=9.4.0
      - setuptools~=67.4.0
      - lime
      - opencv-python
